# Tratamento Dados Faltantes - Licitações

- Identifique qual coluna possui valores faltantes

- Identifique o tipo de dados desta coluna

- Substitua os valores faltantes pelo mesmo formato 

In [43]:
# importando bibliotecas
import pandas as pd
import numpy  as np

In [114]:
licitacoes = pd.read_csv('../../Modulo_3/licitacoes.csv', encoding='ISO-8859-1', sep=';')

## Verificações Gerais

In [115]:
licitacoes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15336 entries, 0 to 15335
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Número Licitação          15336 non-null  int64 
 1   Código UG                 15336 non-null  int64 
 2   Nome UG                   15336 non-null  object
 3   Código Modalidade Compra  15336 non-null  int64 
 4   Modalidade Compra         15336 non-null  object
 5   Número Processo           15336 non-null  object
 6   Objeto                    15336 non-null  object
 7   Situação Licitação        15336 non-null  object
 8   Código Órgão Superior     15336 non-null  int64 
 9   Nome Órgão Superior       15336 non-null  object
 10  Código Órgão              15336 non-null  int64 
 11  Nome Órgão                15336 non-null  object
 12  UF                        15336 non-null  object
 13  Município                 15336 non-null  object
 14  Data Resultado Compra 

Aqui podemos verificar que há dados faltantes na coluna Data Abertura

In [95]:
licitacoes.describe()

Número Licitação      Código UG  Código Modalidade Compra  \
count      1.533600e+04   15336.000000              15336.000000   
mean       1.187265e+07  211458.782016                 -5.994327   
std        7.223749e+07  148542.739765                 33.291265   
min        1.201600e+04   30100.000000                -99.000000   
25%        2.420180e+05  153079.000000                  6.000000   
50%        6.720180e+05  160108.000000                  6.000000   
75%        1.652018e+06  200334.000000                  6.000000   
max        9.962520e+08  926524.000000                 20.000000   

       Código Órgão Superior  Código Órgão  
count           15336.000000  15336.000000  
mean            36443.087898  35072.975548  
std             13783.932637  13538.294712  
min              3000.000000   3000.000000  
25%             26000.000000  26233.000000  
50%             30000.000000  26439.000000  
75%             52000.000000  52111.000000  
max             84000.000000  91081.000000

## Código de Modalidade de Compra

Ao analisar a coluna Código Modalidade Compra, podemos observar que há dados marcados como valores negativos, o que pode significar falta de alguma informação

In [47]:
licitacoes[licitacoes['Código Modalidade Compra']<0]['Modalidade Compra'].unique()

array(['Pregão - Registro de Preço', 'Concorrência - Registro de Preço'],
      dtype=object)

In [48]:
licitacoes[licitacoes['Modalidade Compra']== 'Pregão - Registro de Preço']['Código Modalidade Compra'].unique()

array([-99], dtype=int64)

In [49]:
licitacoes[licitacoes['Modalidade Compra']== 'Concorrência - Registro de Preço']['Código Modalidade Compra'].unique()

array([-97], dtype=int64)

In [50]:
licitacoes['Código Modalidade Compra'].unique()

array([-99,   3,   2,   6,   7,   5,   1,  20, -97,   4], dtype=int64)

como todos os valores -99 são da modalidade de Pregão - Registro de Preço e todos os valores -97 são Código Modalidade Compra, podemos deixar como está, pois não dificulta a análise e pode significar algo importante para o proprietário do arquivo

## Avaliando as datas


In [88]:
import datetime as dt
from dateutil.relativedelta import relativedelta # para calculo com data

In [96]:
licitacoes.head(5)

Número Licitação  Código UG                                       Nome UG  \
0             12016     160438     COMANDO 2 BRIGADA DE CAVALARIA MECANIZADA   
1             12017     160203       2º BATALHAO DE ENGENHARIA DE CONSTRUCAO   
2             12017     193002  DEPARTAMENTO NACIONAL DE OBRAS CONT.AS SECAS   
3             12018     925135              BANCO CENTRAL DO BRASIL - RECIFE   
4             12018     110101     GABINETE DA VICE-PRESIDENCIA DA REPUBLICA   

   Código Modalidade Compra             Modalidade Compra    Número Processo  \
0                       -99    Pregão - Registro de Preço  80871182401201629   
1                         3                  Concorrência  64040053530201713   
2                         2              Tomada de Preços  59400003079201636   
3                         6         Dispensa de Licitação             148097   
4                         7  Inexigibilidade de Licitação  00300000433201818   

                                              Objeto  \
0  Objeto: Pregão Eletrônico - Aquisição de mater...   
1  Objeto: Contratação de empresa para construção...   
2  Objeto: Contratação de empresa especializada n...   
3  Objeto: TV LED de 65 polegadas, UHD 4k, com co...   
4  Objeto: Pretação de serviços de publicação de ...   

               Situação Licitação  Código Órgão Superior  \
0  Evento de Resultado de Julgame                  52000   
1  Evento de Resultado de Julgame                  52000   
2  Evento de Resultado de Julgame                  53000   
3                       Encerrado                  20101   
4                       Publicado                  20000   

                          Nome Órgão Superior  Código Órgão  \
0                        Ministério da Defesa         52121   
1                        Ministério da Defesa         52121   
2  Ministério da Integração e do Desenvolvime         22204   
3                              Sem informação         25201   
4                    Presidência da República         60000   

                                      Nome Órgão  UF   Município  \
0                            Comando do Exército  RS  URUGUAIANA   
1                            Comando do Exército  PI    TERESINA   
2  Departamento Nacional de Obras Contra as Seca  CE   FORTALEZA   
3  BANCO CENTRAL DO BRASIL-ORC.FISCAL/SEG.SOCIAL  -3    Inválido   
4      Gabinete da Vice-Presidência da República  DF    BRASILIA   

  Data Resultado Compra Data Abertura Valor Licitação  
0            04/12/2018    17/08/2016      18854,0000  
1            07/12/2018           NaN     889571,4300  
2            07/12/2018           NaN     865536,6500  
3            04/12/2018    30/11/2018      11075,9900  
4            21/12/2018           NaN      12000,0000

In [116]:
licitacoes['Data Resultado Compra'].unique()

array(['04/12/2018', '07/12/2018', '21/12/2018', '05/12/2018',
       '26/12/2018', '06/12/2018', '17/12/2018', '19/12/2018',
       '27/12/2018', '28/12/2018', '11/12/2018', '31/12/2018',
       '20/12/2018', '03/12/2018', '12/12/2018', '10/12/2018',
       '18/12/2018', '24/12/2018', '13/12/2018', '14/12/2018',
       '01/12/2018', '15/12/2018', '29/12/2018', '22/12/2018',
       '30/12/2018', '08/12/2018', '09/12/2018', '25/12/2018'],
      dtype=object)

In [117]:
# convertendo para datas
licitacoes['Data Resultado Compra'] = pd.to_datetime(licitacoes['Data Resultado Compra'],dayfirst=True, errors='coerce')
licitacoes['Data Abertura'] = pd.to_datetime(licitacoes['Data Abertura'], dayfirst=True, errors='coerce')


In [118]:
licitacoes['Data Resultado Compra'].unique()

<DatetimeArray>
['2018-12-04 00:00:00', '2018-12-07 00:00:00', '2018-12-21 00:00:00',
 '2018-12-05 00:00:00', '2018-12-26 00:00:00', '2018-12-06 00:00:00',
 '2018-12-17 00:00:00', '2018-12-19 00:00:00', '2018-12-27 00:00:00',
 '2018-12-28 00:00:00', '2018-12-11 00:00:00', '2018-12-31 00:00:00',
 '2018-12-20 00:00:00', '2018-12-03 00:00:00', '2018-12-12 00:00:00',
 '2018-12-10 00:00:00', '2018-12-18 00:00:00', '2018-12-24 00:00:00',
 '2018-12-13 00:00:00', '2018-12-14 00:00:00', '2018-12-01 00:00:00',
 '2018-12-15 00:00:00', '2018-12-29 00:00:00', '2018-12-22 00:00:00',
 '2018-12-30 00:00:00', '2018-12-08 00:00:00', '2018-12-09 00:00:00',
 '2018-12-25 00:00:00']
Length: 28, dtype: datetime64[ns]

In [119]:
licitacoes[['Data Resultado Compra', 'Data Abertura']]

Data Resultado Compra Data Abertura
0                2018-12-04    2016-08-17
1                2018-12-07           NaT
2                2018-12-07           NaT
3                2018-12-04    2018-11-30
4                2018-12-21           NaT
...                     ...           ...
15331            2018-12-04    2018-11-26
15332            2018-12-26           NaT
15333            2018-12-03           NaT
15334            2018-12-04           NaT
15335            2018-12-05           NaT

[15336 rows x 2 columns]

In [120]:
licitacoes['Diferenca em Meses'] = (
    (licitacoes['Data Resultado Compra'].dt.year - licitacoes['Data Abertura'].dt.year) * 12 +
    (licitacoes['Data Resultado Compra'].dt.month - licitacoes['Data Abertura'].dt.month)
)

In [121]:
licitacoes['Diferenca em Meses'].unique()

array([28., nan,  1.,  6.,  3.,  0.,  8.,  2.,  4., 14., 29., 18.,  5.,
       11.,  7., 10., 13.,  9., 50., 21., 20., 12.])

Agora podemos usar essa diferença de meses para substituir os valores

In [122]:
mediana = licitacoes['Diferenca em Meses'].median()
mediana = int(mediana.round())
print(mediana)

1


a mediana de diferença de tempo entre a abertura e resultado da compra é de um mês

In [123]:
licitacoes[['Data Abertura','Data Resultado Compra', 'Diferenca em Meses']]

Data Abertura Data Resultado Compra  Diferenca em Meses
0        2016-08-17            2018-12-04                28.0
1               NaT            2018-12-07                 NaN
2               NaT            2018-12-07                 NaN
3        2018-11-30            2018-12-04                 1.0
4               NaT            2018-12-21                 NaN
...             ...                   ...                 ...
15331    2018-11-26            2018-12-04                 1.0
15332           NaT            2018-12-26                 NaN
15333           NaT            2018-12-03                 NaN
15334           NaT            2018-12-04                 NaN
15335           NaT            2018-12-05                 NaN

[15336 rows x 3 columns]

In [124]:
# Subtrair a mediana de meses da 'Data Resultado Compra' para preencher NaT
licitacoes['Data Abertura'] = licitacoes.apply(
    lambda row: row['Data Resultado Compra'] - pd.DateOffset(months=mediana)
    if pd.isna(row['Data Abertura']) else row['Data Abertura'], axis=1
)

In [126]:
# Excluindo a coluna 'Diferenca em Meses' usado para avaliar as datas
licitacoes = licitacoes.drop('Diferenca em Meses', axis=1)

In [127]:
licitacoes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15336 entries, 0 to 15335
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype         
---  ------                    --------------  -----         
 0   Número Licitação          15336 non-null  int64         
 1   Código UG                 15336 non-null  int64         
 2   Nome UG                   15336 non-null  object        
 3   Código Modalidade Compra  15336 non-null  int64         
 4   Modalidade Compra         15336 non-null  object        
 5   Número Processo           15336 non-null  object        
 6   Objeto                    15336 non-null  object        
 7   Situação Licitação        15336 non-null  object        
 8   Código Órgão Superior     15336 non-null  int64         
 9   Nome Órgão Superior       15336 non-null  object        
 10  Código Órgão              15336 non-null  int64         
 11  Nome Órgão                15336 non-null  object        
 12  UF                

## Localização

In [129]:
licitacoes['Município'].unique()

array(['URUGUAIANA', 'TERESINA', 'FORTALEZA', 'Inválido', 'BRASILIA',
       'RIO DE JANEIRO', 'ABADIA DE GOIAS', 'BELEM', 'GUARATINGUETA',
       'PORTO VELHO', 'RECIFE', 'ALTA FLORESTA', 'MARABA',
       'ARRAIAL DO CABO', 'NATAL', 'ARAPIRACA', 'SALVADOR',
       'CORNELIO PROCOPIO', 'PATO BRANCO', 'CAMPO GRANDE', 'BOA VISTA',
       'BAGE', 'IRATI', 'IVAIPORA', 'JABOATAO DOS GUARARAPES',
       'POUSO ALEGRE', 'CAMPOS DOS GOYTACAZES', 'RIO BRANCO',
       'SAPUCAIA DO SUL', 'LAGARTO', 'VITORIA DA CONQUISTA', 'SERRA',
       'GOIANIA', 'MANAUS', 'JUINA', 'CONFRESA', 'GURUPI', 'PARINTINS',
       'PRESIDENTE FIGUEIREDO', 'SAO GABRIEL DA CACHOEIRA', 'ALTAMIRA',
       'PETROLINA', 'CURITIBA', 'NITEROI', 'LAGES', 'SAO PAULO',
       'SAO LUIS', 'LIMEIRA', 'JOINVILLE', 'SANTA CRUZ DO SUL', 'MOSSORO',
       'DUQUE DE CAXIAS', 'MACAPA', 'VILA VELHA', 'PORTO ALEGRE',
       'SANTA TERESA', 'RIO LARGO', 'MACEIO', 'TABATINGA', 'CACOAL',
       'VITORIA', 'CORUMBA', 'ARACAJU', 'FOZ DO IGUACU'

podemos observar que há 'Inválido' entre municípios

In [136]:
licitacoes[licitacoes['Município'] == 'Inválido'][['UF', 'Município']].head(10)

UF Município
3     -3  Inválido
165   -3  Inválido
345   -3  Inválido
346   -3  Inválido
528   -3  Inválido
695   -3  Inválido
1617  -3  Inválido
1812  -3  Inválido
1993  -3  Inválido
1994  -3  Inválido

Temos o que todos os municípios inválidos tem UF -3

In [138]:
len(licitacoes[licitacoes['Município'] == 'Inválido'])

168

In [134]:
licitacoes['UF'].unique()

array(['RS', 'PI', 'CE', '-3', 'DF', 'RJ', 'GO', 'PA', 'SP', 'RO', 'PE',
       'MT', 'RN', 'AL', 'BA', 'PR', 'MS', 'RR', 'MG', 'AC', 'SE', 'ES',
       'AM', 'TO', 'SC', 'MA', 'AP', 'PB'], dtype=object)

In [140]:
len(licitacoes[licitacoes['UF'] == '-3'])

168

Deveriamos analisar linha a linha e buscar informações sobre as colunas UF e Municípios

## Float como string

In [146]:
licitacoes['Valor Licitação'] = licitacoes['Valor Licitação'].str.replace(',','.').astype(float)

In [148]:
licitacoes.describe()
# agora o valor de licitação aparece no describe

Número Licitação      Código UG  Código Modalidade Compra  \
count      1.533600e+04   15336.000000              15336.000000   
mean       1.187265e+07  211458.782016                 -5.994327   
min        1.201600e+04   30100.000000                -99.000000   
25%        2.420180e+05  153079.000000                  6.000000   
50%        6.720180e+05  160108.000000                  6.000000   
75%        1.652018e+06  200334.000000                  6.000000   
max        9.962520e+08  926524.000000                 20.000000   
std        7.223749e+07  148542.739765                 33.291265   

       Código Órgão Superior  Código Órgão Data Resultado Compra  \
count           15336.000000  15336.000000                 15336   
mean            36443.087898  35072.975548   2018-12-12 23:33:20   
min              3000.000000   3000.000000   2018-12-01 00:00:00   
25%             26000.000000  26233.000000   2018-12-06 00:00:00   
50%             30000.000000  26439.000000   2018-12-10 00:00:00   
75%             52000.000000  52111.000000   2018-12-20 00:00:00   
max             84000.000000  91081.000000   2018-12-31 00:00:00   
std             13783.932637  13538.294712                   NaN   

                       Data Abertura  Valor Licitação  
count                          15336     1.533600e+04  
mean   2018-11-15 00:50:47.887323904     5.805981e+05  
min              2014-10-22 00:00:00     0.000000e+00  
25%              2018-11-06 00:00:00     1.945912e+03  
50%              2018-11-14 00:00:00     7.500000e+03  
75%              2018-11-27 00:00:00     3.250000e+04  
max              2018-12-31 00:00:00     9.689600e+08  
std                              NaN     1.106470e+07